apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080  # External port
    targetPort: 8080  # Backend container port
  type: ClusterIP  # Internal communication within the cluster
