version: "3.8"

services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_CONNECTION_STRING: mongodb://mongo:27017/user
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
